import Config

config :logger, :console,
  metadata: [
    :activity_id,
    :activity_type,
    :activities,
    :address,
    :args,
    :args_count,
    :attempt,
    :backoff_ms,
    :count,
    :error,
    :executors,
    :failures,
    :has_details,
    :has_heartbeat_timeout,
    :is_local,
    :jobs,
    :message,
    :module,
    :name,
    :namespace,
    :protocol_instance_id,
    :query_name,
    :query_type,
    :reason,
    :registered_types,
    :run_id,
    :seq,
    :signal,
    :signal_name,
    :span_id,
    :span_kind,
    :task_queue,
    :task_token_len,
    :timeout,
    :type,
    :update_name,
    :workflow_id,
    :workflows,
    :workflow_type
  ]
